#!/bin/bash
#
# saiku-server    This shell script takes care of starting and stopping saiku-server 
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: saiku-server
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: Modular open-source analysis suite offering lightweight OLAP which remains easily embeddable, extendable and configurable.
# Short-Description: start and stop saiku-server
### END INIT INFO

## Source function library.
#. /etc/rc.d/init.d/functions
SAIKU_HOME=/usr/share/saiku-server
SHUTDOWN_WAIT=20

saiku_pid() { 
  echo `ps aux | grep saiku-server/tomcat/conf/logging.properties | grep -v grep | awk '{ print $2 }'`
}

start() {
  pid=$(saiku_pid)
  if [ -n "$pid" ] 
  then
    echo "saiku-server is already running (pid: $pid)"
  else
    # Start tomcat
    echo "Starting saiku-server"
    ulimit -n 100000
    umask 007
    /bin/su -p -s /bin/sh saiku-server $SAIKU_HOME/start-saiku.sh
  fi


  return 0
}

stop() {
  pid=$(saiku_pid)
  if [ -n "$pid" ]
  then
    echo "Stoping saiku-server"
    /bin/su -p -s /bin/sh saiku-server $SAIKU_HOME/stop-saiku.sh

    let kwait=$SHUTDOWN_WAIT
    count=0;
    until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]
    do
      echo -n -e "\nwaiting for processes to exit";
      sleep 1
      let count=$count+1;
    done

    if [ $count -gt $kwait ]; then
      echo -n -e "\nkilling processes which didn't stop after $SHUTDOWN_WAIT seconds"
      kill -9 $pid
    fi
  else
    echo "saiku-server is not running"
  fi
 
  return 0
}

case $1 in
start)
  start
;; 
stop)   
  stop
;; 
restart)
  stop
  start
;;
status)
  pid=$(saiku_pid)
  if [ -n "$pid" ]
  then
    echo "saiku-server is running with pid: $pid"
  else
    echo "saiku-server is not running"
  fi
;; 
esac    
exit 0
